---
defaults:
  system_settings:
    apic_connectivity_preference:
      interface_to_use_for_external_connections: inband
    bgp_route_reflector:
      autonomous_system_number: 65000
      # Remember to Test without
      pods:
        - pod: 1
          route_reflector_nodes: [101, 102]
    coop_group:
      annotation: ''
      type: strict
    endpoint_controls:
      annotation: ''
      ep_loop_protection:
        action:
          bd_learn_disable: false
          port_disable: true
        administrative_state: enabled
        loop_detection_interval: 60
        loop_detection_multiplier: 4
      ip_aging:
        administrative_state: enabled
      rouge_ep_control:
        administrative_state: enabled
        hold_interval: 1800
        rouge_interval: 30
        rouge_multiplier: 6
    fabric_wide_settings:
      annotation: ''
      disable_remote_ep_learning: true
      enforce_domain_validation: true
      enforce_epg_vlan_validation: false
      enforce_subnet_check: true
      leaf_opflex_client_authentication: true
      leaf_ssl_opflex: true
      reallocate_gipo: false
      restrict_infra_vlan_traffic: false
      ssl_opflex_versions:
        TLSv1: false
        TLSv1_1: false
        TLSv1_2: true
      spine_opflex_client_authentication: true
      spine_ssl_opflex: true
    global_aes_encryption_settings:
      clear_passphrase: false
      enable_encryption: true
      passphrase_key_derivation_version: v1
    isis_policy:
      annotation: ''
      isis_mtu: 1492
      isis_metric_for_redistributed_routes: 63
      lsp_fast_flood_mode: enabled
      lsp_generation_initial_wait_interval: 50
      lsp_generation_maximum_wait_interval: 8000
      lsp_generation_second_wait_interval: 50
      sfp_computation_frequency_initial_wait_interval: 50
      sfp_computation_frequency_maximum_wait_interval: 8000
      sfp_computation_frequency_second_wait_interval: 50
    port_tracking:
      annotation: ''
      delay_restore_timer: 120
      include_apic_ports: false
      number_of_active_ports: 0
      port_tracking_state: on
    ptp_and_latency_measurement:
      annotation: ''
      announce_interval: 1
      announce_timeout: 3
      delay_request_interval: -2
      global_domain: 0
      global_priority_1: 255
      global_priority_2: 255
      precision_time_protocol: enabled
      ptp_profile: AES67-2015
      sync_interval: -3
